### PR TITLE
Change project that images will live in

### PR DESCRIPTION
**Pull request by Fryguy**
@carbonin @bdunne Please review.  This is just a stab at getting this in...I'm not sure this is actually the right way.

### CODE REVIEW

**Comment by carbonin** [comment]
Think I would rather turn these into templates so that we don't have to dirty the git history if we want to deploy from somewhere else.

I can open a PR if you want.

**Comment by carbonin** [comment]
Like this https://github.com/ManageIQ/topological_inventory-deploy/pull/8/files

**Comment by Fryguy** [comment]
I'm not sure I understand the difference between the deployment config and the deployment config template.  Even so, is that something for this PR?

**Comment by carbonin** [comment]
A deployment config would be created directly with something like `oc apply -f deployment_config.yaml`

A template has parameters that you can substitute in. So in this case I could run either `oc process -f deployment_config_template.yaml | oc apply -f -` to take the default value, or run `oc process -f deployment_config_template.yaml -p IMAGE_NAMESPCE=nick-test-project | oc apply -f -`

Right now if I wanted to deploy an image that I pushed to the `nick-test-project` namespace, I would have to edit the deployment_config.yaml file, if it's a template I can do it with a command.

**Comment by Fryguy** [comment]
I'll close this and we can discuss if we want to get it in this way, or if we just want to go the BuildConfig route entirely...I was trying to get to a stopgap solution where Travis continues to build but pushes into the new namespace.

**Pull request closed without merging**
